### ISSUE TITLE
Uncaught TypeError: Cannot set property 'textContent' of null

### ISSUE THREAD

**Issue by ryanlabelle** [wpmetabox/mb-yoast-seo#1]
LOVE this plugin, wow has it added so much value. Thank you!

On some pages, not all I get this JS console error and I'm trying to trace it but so far I haven't been able to resolve. Anyone else come across this?

http://new.tinygrab.com/6407caa59edf1d844891ca7f64a3d060b2ab860772.png

and

http://new.tinygrab.com/6407caa59e26aa78d3a5194aac78ba423aa67efbdd.png

**Comment by rilwis** [comment]
Can you give me more info about the buggy page? From the console, it says the bug appears in the code of Yoast plugin's file. I guess it might conflict with other parts of the admin screen.

**Comment by ryanlabelle** [comment]
Is it possible to give you private access to the site? I've been having a hard time tracking the error to it's source.

**Comment by rilwis** [comment]
No problem, please send me via the contact form at https://metabox.io

**Comment by ryanlabelle** [comment]
Thank you! I just sent the info. :)

**Comment by MickeyKay** [comment]
Same issue - any update?

**Comment by ryanlabelle** [comment]
@MickeyKay is this in your own project or part of a theme?

**Comment by rilwis** [comment]
Just pushed a fix for that. Can you please try? 3f6af7c8185e835fdf1cd9c82c23f7a9a0d7eacb

**Comment by ryanlabelle** [comment]
Thanks. Tested and left a comment here: https://github.com/rilwis/mb-yoast-seo/commit/3f6af7c8185e835fdf1cd9c82c23f7a9a0d7eacb

**Comment by ryanlabelle** [comment]
Hi guys. I noticed something interesting with this issue that just started popping up for me. What solved the issues last time was having the Content Editor tab switched from Visual to Text. I didn't realize it at the time but as soon as I switch back to Visual and save changes the site reloads with that error message. 

Uncaught TypeError: Cannot set property 'textContent' of null

Would you mind testing just to see if you can reproduce the error? I'm using the latest version of Meta box and meta box for yoast.

Thank you for looking into it.

**Comment by aishoo1612** [comment]
I was using darkskynet api and  i keep on getting same error after i am setting DOM elements
 let temperatureDegree = document.querySelector(".temperature-degree");
    let locationTimezone = document.querySelector(".location-timezone");
    let temperatureDescription = document.querySelector(".temperature-descritption");
  temperatureDegree.textContent = temperature;
                    temperatureDescription.textContent = summary ;       
                    locationTimezone.textContent= data.timezone ;     
pls help !!
