### ISSUE TITLE
script.js not enqueued

### ISSUE THREAD

**Issue by ryanlabelle** [wpmetabox/mb-yoast-seo#2]
- Meta box version 4.8.7
- meta box for yoast seo version 1.1.1
- yoast seo version 3.2.5
- wordpress 4.5.2

script.js is not enqueued (line 30 of mb-yoast-seo.php). When I remove the 'yoast-seo' dependency in the wp_enqueue_script statement it is included. However that creates a js error.

http://new.tinygrab.com/6407caa59e5aedcf23a9bb78b4dded2c23d83ad993.png

**Comment by ryanlabelle** [comment]
FYI, I tested with Yoast SEO version 3.1 and it things started to work again, so something must have been updated with Yoast recently to cause a conflict. 

Do you have enough info?

Cheers.

**Comment by ryanlabelle** [comment]
Hi guys, any news on this one? Are you phasing this plugin out?

Cheers.

**Comment by rilwis** [comment]
Hi, sorry for getting back late. I've just updated the plugin with the fix for this.

Yoast team changes the JS very frequently :(

**Comment by ryanlabelle** [comment]
Thanks!
